[package]
name = "segul_api"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
segul = "0.19.*"
flutter_rust_bridge = "*"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
