name: releases

on:
  push:
    branches:
      - releases

jobs:
  release:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          flutter pub get
          flutter analyze

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build
        uses: subosito/flutter-action@v2
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
          flutter build linux --release
      - if: ${{ matrix.os == 'windows-latest' }}
        run: |
          flutter build windows --release
          flutter build apk --release

      - name: Compress Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo "Compressing files..."
          tar -czvf segui.tar.gz build/linux/x64/release/bundle

      - name: Compress Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "Compressing files..."
          powershell Compress-Archive -Path build\windows\runner\Release -DestinationPath segui.zip

      - name: Upload linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: segui.tar.gz
          asset_name: segui-Linux-x86_64.tar.gz
          tag: ${{ github.ref_name }}

      - name: Upload windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: segui.zip
          asset_name: segui-Windows-x86_64.zip
          tag: ${{ github.ref_name }}

      - name: Upload android
        if: ${{ matrix.os == 'windows-latest' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: segui-Android.apk
          tag: ${{ github.ref_name }}
